000100871103      ****************************************************************
000200000727      * APPLICATION NAME...........: . ALL APPLICATIONS              *
000300000727      * COPY NAME..................: . WKSPECNAMES                   *
000400000727      * COPY TYPE..................: . DEFINITION GENERAL FIELD      *
000500000727      * FUNCTION...................: . SPECIAL-NAMES                 *
000600000727      * COPY LOCATION..............: . AFTER OBJECT-COMPUTER         *
000700871103      ****************************************************************
000800871103       SPECIAL-NAMES.   I-O-FEEDBACK    IS IO-INFO
000900870423                        OPEN-FEEDBACK   IS OPEN-INFO
001000871103                        CONSOLE         IS OPERATEUR
001100871103                        LOCAL-DATA      IS LDA
001200871103                        REQUESTOR       IS ECRAN
001300871103                        UPSI-0          IS SW0
001400871103                            ON STATUS   IS SW0-ON
001500871103                        UPSI-1          IS SW1
001600871103                            ON STATUS   IS SW1-ON
001700871103                        UPSI-2          IS SW2
001800871103                            ON STATUS   IS SW2-ON
001900871103                        UPSI-3          IS SW3
002000871103                            ON STATUS   IS SW3-ON
002100871103                        UPSI-4          IS SW4
002200871103                            ON STATUS   IS SW4-ON
002300871103                        UPSI-5          IS SW5
002400871103                            ON STATUS   IS SW5-ON
002500871103                        UPSI-6          IS SW6
002600871103                            ON STATUS   IS SW6-ON
002700871103                        UPSI-7          IS SW7
002800871103                            ON STATUS   IS SW7-ON
002900870423                        SYSTEM-SHUTDOWN IS SYSTEME-STATUS
003000870423                              ON STATUS IS FIN-SYSTEME
003100870423                        DECIMAL-POINT   IS COMMA.
003200870422      *
